addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.13.1")
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.23.0")
addSbtPlugin("com.github.sbt" % "sbt-github-actions" % "0.29.0")
addSbtPlugin("org.playframework.twirl" % "sbt-twirl" % "2.0.9")
addSbtPlugin("com.typesafe" % "sbt-mima-plugin" % "1.1.5")
addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.3")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.8.2")
